input {
  beats {
    port => 5044
  }
}

filter {
  if [kubernetes][container][name] == "analytics-api" {
    mutate { add_tag => ["api"] }
  } else if [kubernetes][container][name] == "risk-engine" {
    mutate { add_tag => ["risk_engine"] }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "finsight-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
